- name: play level variables
  hosts: local
  conenction: local
  vars_files:
    - course.yaml
  tasks:
  - name: print variables
    vars:
     COURSE: Ansible
    ansible.builtin.debug:
     sg: "Course is {{ COURSE }}, Trainer is: {{ TRAINER }}"

